name: peda
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip=23.0
  - setuptools=65.5.1
  - numpy<2

  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0

  - cython
  - cmake
  - swig
  - opencv
  - glfw
  - glew